# Generated by Django 5.0 on 2024-01-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletags_tag_articletags_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
